
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi
  namespace: services-namespace
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: catalogapi
      app-type: microservice
      release: "1.0"
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: catalogapi
        app-type: microservice
        release: "1.0"
    spec:
      containers:
      - name: catalogapi
        image: 8920057852/catalogapi:1.0
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: DatabaseSettings
          value: "ConnectionString=mongodb://catalogdb:27017" 