apiVersion: v1
kind: Service
metadata:
  name: catalogdb
  namespace: database-namespace

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: catalogdb
    app-type: database-mongodb
    release: "0"

  ports:
    - name: http
      port: 27017
      nodePort: 30017

  type: NodePort