
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb
  namespace: database-namespace
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: catalogdb
      app-type: database-mongodb
      release: "0"
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: catalogdb
        app-type: database-mongodb
        release: "0"
    spec:
      containers:
      - name: catalogdb
        image: mongo